on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' || github.event.sender.login == 'devin-ai-integration' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: docker://codiumai/pr-agent:0.29-github_action
        env:
          CONFIG.MODEL: "gpt-4.1"
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          response_language: "ja-JP"
          pr_description.extra_instructions: "必ず全て日本語で記述してください。" 
          pr_reviewer.extra_instructions: "必ず全て日本語で記述してください。" 
          pr_code_suggestions.extra_instructions: "必ず全て日本語で記述してください。" 
          pr_update_changelog.extra_instructions: "必ず全て日本語で記述してください。" 
